[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse2,+ssse3,+sse4.1,+sse4.2", "--cfg", "tokio_unstable"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+sse2,+ssse3,+sse4.1,+sse4.2", "--cfg", "tokio_unstable"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+neon", "--cfg", "tokio_unstable"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+sse2,+ssse3,+sse4.1,+sse4.2", "--cfg", "tokio_unstable"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon", "--cfg", "tokio_unstable"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+sse2,+ssse3,+sse4.1,+sse4.2", "--cfg", "tokio_unstable"]
